backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Strona główna"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
          - { label: Główny obraz, name: bigImage, widget: image }
          - {
              label: Slider,
              name: slider_captions,
              widget: list,
              fields:
                [
                  { label: Tytuł, name: title, widget: string },
                  { label: Opis, name: caption, widget: string },
                ],
            }
          - {
              label: Sekcje pomiędzy karuzelą a polecanymi,
              name: welcomeSections,
              widget: object,
              fields:
                [
                  {
                    label: Sekcja,
                    name: sections,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Subtitle, name: subtitle, widget: string },
                        {
                          label: Button Text,
                          name: buttonText,
                          widget: string,
                        },
                        {
                          label: Button Link,
                          name: buttonLink,
                          widget: string,
                        },
                        {
                          label: Is external link,
                          name: isExternal,
                          widget: "select",
                          options:
                            [
                              { label: "Tak", value: true },
                              { label: "Nie", value: false },
                            ],
                        },
                        { label: Text, name: text, widget: markdown },
                      ],
                  },
                ],
            }
          - {
              label: Tekst SEO,
              name: offerings,
              widget: object,
              fields:
                [
                  {
                    label: Sekcja,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: markdown },
                      ],
                  },
                ],
            }
          - {
              label: Sekcje nad belkami z kategoriami,
              name: imageBoxSections,
              widget: object,
              fields:
                [
                  {
                    label: Sekcja,
                    name: sections,
                    widget: list,
                    fields:
                      [
                        { label: Obraz, name: image, widget: file },
                        {
                          label: Tekst na zdjęciu,
                          name: imageText,
                          widget: markdown,
                        },
                        {
                          label: Tekst pzycisku na zdjęciu,
                          name: imageButtonText,
                          widget: string,
                        },
                        {
                          label: Link przycisku na zdjęciu Link,
                          name: imageButtonLink,
                          widget: string,
                        },
                        {
                          label: Is external link ?,
                          name: imageIsExternal,
                          widget: "select",
                          options:
                            [
                              { label: "Tak", value: true },
                              { label: "Nie", value: false },
                            ],
                        },
                        {
                          label: Tekst na zdjęciu,
                          name: whiteBoardText,
                          widget: markdown,
                        },
                        {
                          label: Tekst pzycisku na białym tle,
                          name: whiteBoardButtonText,
                          widget: string,
                        },
                        {
                          label: Link przycisku na białym tle,
                          name: whiteBoardButtonLink,
                          widget: string,
                        },
                        {
                          label: Is external link ?,
                          name: whiteBoardIsExternal,
                          widget: "select",
                          options:
                            [
                              { label: "Tak", value: true },
                              { label: "Nie", value: false },
                            ],
                        },
                      ],
                  },
                ],
            }
      - file: "src/pages/uslugi/index.md"
        label: "Strona Usługi"
        name: "services-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
          - { label: Główny obraz, name: bigImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/montaz/index.md"
        label: "Strona Montaż"
        name: "assembly-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "assembly-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
          - { label: Główny obraz, name: bigImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/serwis/index.md"
        label: "Strona Serwis"
        name: "service-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "service-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
          - { label: Główny obraz, name: bigImage, widget: image }
          - {
              label: Tematy,
              name: threads,
              widget: list,
              fields: [{ label: Temat, name: thread, widget: string }],
            }
          - {
              label: Dane kontaktowe,
              name: contacts,
              widget: list,
              fields:
                [
                  { label: Kontakt, name: contact, widget: string },
                  {
                    label: "Typ",
                    name: "type",
                    widget: "select",
                    options:
                      [
                        { label: "Mail", value: "mail" },
                        { label: "Telefon", value: "phone" },
                      ],
                  },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/firma/index.md"
        label: "Strona o firmie"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
          - { label: Główny obraz, name: bigImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/rodo/index.md"
        label: "Strona RODO"
        name: "rodo"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "rodo-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
          - { label: Główny obraz, name: bigImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/polityka-prywatnosci/index.md"
        label: "Strona Polityka prywatności"
        name: "privacy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "privacy-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
          - { label: Główny obraz, name: bigImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/producenci/index.md"
        label: "Strona producenci"
        name: "producents-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "producents-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
          - { label: Główny obraz, name: bigImage, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: Producenci,
              name: producents,
              widget: list,
              fields:
                [
                  { label: Obraz, name: cover, widget: image },
                  { label: Nazwa, name: name, widget: string },
                  { label: Opis, name: description, widget: "markdown" },
                  { label: Adres www, name: link, widget: string },
                ],
            }
      - file: "src/pages/kontakt/index.md"
        label: "Strona Kontakt"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "text",
            }
          - { label: Główny obraz, name: bigImage, widget: image }
          - {
              label: Tematy,
              name: threads,
              widget: list,
              fields: [{ label: Temat, name: thread, widget: string }],
            }
          - {
              label: Dane kontaktowe,
              name: contacts,
              widget: list,
              fields:
                [
                  { label: Kontakt, name: contact, widget: string },
                  {
                    label: "Typ",
                    name: "type",
                    widget: "select",
                    options:
                      [
                        { label: "Mail", value: "mail" },
                        { label: "Telefon", value: "phone" },
                      ],
                  },
                ],
            }
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article-page",
        }
      - { label: "Order", name: "order", widget: "number", valueType: "int" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string" }
      - { label: "Meta Description", name: "meta_description", widget: "text" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover", name: "cover", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "products"
    label: "Produkty"
    folder: "src/pages/produkty"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "product-page",
        }
      - {
          label: "Order",
          name: "order",
          widget: number,
          valueType: int,
          default: 0,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Meta Description", name: "meta_description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover", name: "cover", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Kategoria", name: "categories", widget: "string" }
      - { label: "Producent", name: "producent", widget: "string" }
      - {
          label: "Wyróżnij produkt",
          name: "hotProductsSelect",
          widget: "select",
          options:
            [{ label: "Tak", value: "tak" }, { label: "Nie", value: "nie" }],
        }
      - {
          label: Zdjęcia,
          name: images,
          widget: list,
          fields:
            [
              { label: Zdjęcie, name: image, widget: image },
              { label: Podpis, name: caption, widget: string },
            ],
        }
      - {
          label: Wersje,
          name: version,
          widget: list,
          fields:
            [
              { label: Moc, name: power, widget: string },
              { label: Cena, name: price, widget: string },
            ],
        }
      - { label: Informacja o Vat, name: vat, widget: markdown }
